on:
  push:
    branches: [ production ]

name: Deploy to Cloudflare Pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true # Will run `bundle install` and cache gems

      - name: Build site
        run: ./tasks/start.sh production
        run: |
          echo env.GITHUB_HEAD_REF
          echo env.GITHUB_REF_NAME

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: eliottvincent-com
          directory: build
          branch: production